# Generated by Django 5.2 on 2025-06-12 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auteur',
            name='photo',
        ),
        migrations.AddField(
            model_name='jeu',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auteur',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='jeu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.jeu'),
        ),
        migrations.AlterField(
            model_name='jeu',
            name='annee_sortie',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jeu',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.auteur'),
        ),
        migrations.AlterField(
            model_name='jeu',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.categorie'),
        ),
        migrations.AlterField(
            model_name='jeu',
            name='editeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.editeur'),
        ),
        migrations.AlterField(
            model_name='jeu',
            name='photo_boite',
            field=models.ImageField(blank=True, null=True, upload_to='boites/'),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
